#ifndef RESOURCESYSTEMTYPES_H
#define RESOURCESYSTEMTYPES_H

#ifdef COMPILER_MSVC
#pragma once
#endif

enum ResourceLeakTrackingGroup_t
{
	RLTG_GENERAL_REFERENCE = 0,
	RLTG_MANIFEST_REFERENCE,
	RLTG_STRONGHANDLE,
	RLTG_SCHEMA_REFERENCE,
};

#endif // RESOURCESYSTEMTYPES_H
